### PR TITLE
Added USWDS framework 

### PR DESCRIPTION
**Pull request by cameroncowden**
To preview you should be able to clone locally and `bundle install` then `bundle exec jekyll serve`

Todo's for pushing this live would be 

- swapping out hero image on homepage, 
- fleshing out the text in the second section homepage, 
- replacing the placeholder text with real stuff (maybe speak to the challenges with the current data availability, things people could do or build with this data, etc), 
- removing temporary footer links (leaving for now to showcase those two features if you want to use them later)

### CODE REVIEW

**Comment by cameroncowden** [comment]
image
image

**Comment by diafygi** [comment]
@cameroncowden Thanks! Will review when I have a chance.

**Comment by diafygi** [comment]
@cameroncowden An update, I added the USWDS framework as an alternate default layout and converted the landing and about-us pages to use it (just to make sure all the links/menus/assets/etc. work correctly). Will start integrating your changes from the API docs pages as a next step (not sure how soon I can get to it, though).

**Comment by daniel-utilityapi** [comment]
@cameroncowden I used your pull request as a reference in going through the website and converting it to use USWDS. Thanks!

**Comment by diafygi** [comment]
@cameroncowden I used your pull request as reference and went through and converted the existing website to use USWDS. Thanks!

**Pull request closed without merging**
